[package]
name = "lettuce"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
glommio = "0.8.0"
memmap2 = "0.9.4"
proptest = "1.4.0"
