[toolchain]
channel = "nightly"
# todo: eventually this will only target x86 but devloping on linux is inconvenient
# replace me if/when adding async io_uring, accessing or shimming it out to O_DIRECT
# targets = ["x86_64-unknown-linux-gnu"]
